### ISSUE TITLE
r-adj策略在sgl模型上的性能

### ISSUE THREAD

**Issue by ahukmr** [fuxiAIlab/r-AdjNorm#3]
作者您好，请问您在sgl上运用r-adj策略时，对于推荐主任务的对原图用的归一化系数是0.5还是0.75呀？文章中提到的在sgl达到最佳效果的r=0.75是在两个增强视图中用r=0.75的图卷积做的吗？

**Comment by Zhaominghao1314** [comment]
欢迎关注我们的工作！我们在sgl中使用r-adjnorm时，保持原图以及增强图邻接矩阵的normlization系数（r）相同。
